# Generated by Django 2.1.4 on 2018-12-11 10:35

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributeConstraint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('attribute', models.CharField(max_length=120, verbose_name='Attribut')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='Valeur minimale')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='Valeur maximale')),
            ],
            options={
                'verbose_name': 'Contrainte',
                'verbose_name_plural': 'Contraintes',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('ECTS', models.FloatField(verbose_name='ECTS')),
                ('period', models.CharField(max_length=20, verbose_name='Période')),
                ('location', models.CharField(blank=True, max_length=120, null=True, verbose_name='Lieu')),
                ('time', models.CharField(blank=True, max_length=120, null=True, verbose_name='Horaires')),
                ('attributes', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
                ('short_name', models.CharField(max_length=10, verbose_name='Nom court')),
                ('attribute_constraints', models.ManyToManyField(blank=True, related_name='attribute_constraints', to='parcours_imi.AttributeConstraint')),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nom')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourseChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Commentaire')),
                ('submitted', models.BooleanField(default=False, verbose_name="Validé par l'étudiant")),
                ('main_courses', models.ManyToManyField(blank=True, related_name='main_courses', to='parcours_imi.Course')),
                ('option_courses', models.ManyToManyField(blank=True, related_name='option_courses', to='parcours_imi.Course')),
            ],
            options={
                'verbose_name': 'Choix de cours',
                'verbose_name_plural': 'Choix de cours',
            },
        ),
        migrations.CreateModel(
            name='UserParcours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_choice', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcours', to='parcours_imi.UserCourseChoice')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parcours_imi.Master')),
                ('option', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='parcours_imi.Option')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parcours étudiant',
                'verbose_name_plural': 'Parcours étudiants',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='available_options',
            field=models.ManyToManyField(related_name='available_options', to='parcours_imi.Option'),
        ),
        migrations.AddField(
            model_name='course',
            name='masters',
            field=models.ManyToManyField(related_name='masters', to='parcours_imi.Master'),
        ),
    ]
