# Generated by Django 2.0.5 on 2018-05-27 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import parcours_imi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obligatoire', models.BooleanField(default=0)),
                ('title', models.CharField(max_length=100)),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
                ('ects', models.FloatField()),
                ('semester', models.PositiveSmallIntegerField()),
                ('days', models.CharField(choices=[('Mo', 'Lundi'), ('Tu', 'Mardi'), ('We', 'Mercredi'), ('Th', 'Jeudi'), ('Fr', 'Vendredi')], max_length=2)),
                ('duration', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('troisa_possible', models.BooleanField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('nb_cours', models.PositiveSmallIntegerField(default=0)),
                ('nb_ects_cours', models.FloatField(default=0)),
                ('nb_projet', models.PositiveSmallIntegerField(default=0)),
                ('nb_ects_projet', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.ManyToManyField(to='parcours_imi.Course')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parcours_imi.Master')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcours_imi.Master'),
        ),
    ]
