# Generated by Django 2.1 on 2018-09-15 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercoursechoice',
            options={'verbose_name': 'Choix de cours', 'verbose_name_plural': 'Choix de cours'},
        ),
    ]
