# Generated by Django 2.0.5 on 2018-06-04 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='parcours_imi.Master'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcours_imi.models.Formula'),
        ),
    ]
