# Generated by Django 2.1 on 2018-09-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0002_auto_20180915_1025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='master',
        ),
        migrations.AddField(
            model_name='course',
            name='masters',
            field=models.ManyToManyField(related_name='masters', to='parcours_imi.Master'),
        ),
        migrations.AlterField(
            model_name='master',
            name='short_name',
            field=models.CharField(max_length=10, verbose_name='Nom court'),
        ),
    ]
