# Generated by Django 2.1.1 on 2018-12-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0003_auto_20180929_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Lieu'),
        ),
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Horaires'),
        ),
    ]
