# Generated by Django 2.0.6 on 2018-06-05 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parcours_imi', '0004_auto_20180604_2012'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserParcours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formula', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Parcours étudiant',
                'verbose_name_plural': 'Parcours étudiants',
            },
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='master',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.RenameField(
            model_name='course',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='days',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='obligatoire',
        ),
        migrations.RemoveField(
            model_name='master',
            name='troisa_possible',
        ),
        migrations.AlterField(
            model_name='course',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcours_imi.Master'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='userparcours',
            name='courses',
            field=models.ManyToManyField(to='parcours_imi.Course'),
        ),
        migrations.AddField(
            model_name='userparcours',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parcours_imi.Master'),
        ),
        migrations.AddField(
            model_name='userparcours',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
