# Generated by Django 2.0.7 on 2018-07-29 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0004_auto_20180729_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userparcours',
            old_name='formula',
            new_name='option',
        ),
    ]
