# Generated by Django 2.0.7 on 2018-07-29 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0005_auto_20180729_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursechoice',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Commentaire'),
        ),
    ]
