# Generated by Django 2.0.7 on 2018-07-29 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0006_auto_20180729_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoursechoice',
            name='option2_courses',
        ),
        migrations.AddField(
            model_name='usercoursechoice',
            name='option_courses',
            field=models.ManyToManyField(blank=True, related_name='option_courses', to='parcours_imi.Course'),
        ),
        migrations.AlterField(
            model_name='usercoursechoice',
            name='main_courses',
            field=models.ManyToManyField(blank=True, related_name='main_courses', to='parcours_imi.Course'),
        ),
        migrations.AlterField(
            model_name='userparcours',
            name='option',
            field=models.CharField(blank=True, choices=[('3A-ecole', '3A École'), ('3A-M2-PFE', '3A M2 Imbriqués - Option 1'), ('3A-M2-ECTS', '3A M2 Imbriqués - Option 2')], default=None, max_length=120, null=True),
        ),
    ]
