# Generated by Django 2.1 on 2018-09-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0009_auto_20180903_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='semester',
            new_name='period',
        ),
    ]
