# Generated by Django 2.0.6 on 2018-07-09 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0010_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userparcours',
            name='comment',
            field=models.TextField(default='', verbose_name='Commentaire'),
        ),
        migrations.AddField(
            model_name='userparcours',
            name='submitted',
            field=models.BooleanField(default=False, verbose_name="Validé par l'étudiant"),
        ),
        migrations.AlterField(
            model_name='userparcours',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='courses', to='parcours_imi.Course'),
        ),
        migrations.AlterField(
            model_name='userparcours',
            name='coursesOption2',
            field=models.ManyToManyField(blank=True, related_name='coursesOption2', to='parcours_imi.Course'),
        ),
    ]
