# Generated by Django 2.1 on 2018-09-03 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0010_auto_20180903_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userparcours',
            name='course_choice',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcours', to='parcours_imi.UserCourseChoice'),
        ),
    ]
