# Generated by Django 2.0.6 on 2018-07-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0011_auto_20180709_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userparcours',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Commentaire'),
        ),
    ]
