# Generated by Django 2.0.5 on 2018-06-04 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0002_auto_20180604_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='parcours_imi.Master'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='courses',
            field=models.ManyToManyField(related_name='profiles', to='parcours_imi.Courses'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='parcours_imi.models.Formula'),
        ),
    ]
