# Generated by Django 2.0.6 on 2018-06-04 20:12

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('parcours_imi', '0003_auto_20180604_1451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
    ]
