# Generated by Django 2.0.6 on 2018-06-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0005_auto_20180605_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='course',
            name='long',
        ),
        migrations.AddField(
            model_name='course',
            name='location',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='master',
            name='website',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='userparcours',
            name='formula',
            field=models.CharField(max_length=120),
        ),
    ]
