# Generated by Django 2.0.6 on 2018-06-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0006_auto_20180605_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ects',
        ),
        migrations.AddField(
            model_name='course',
            name='ECTS',
            field=models.FloatField(default=0, verbose_name='ECTS'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userparcours',
            name='coursesOption2',
            field=models.ManyToManyField(related_name='coursesOption2', to='parcours_imi.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='location',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.PositiveSmallIntegerField(verbose_name='Semestre'),
        ),
        migrations.AlterField(
            model_name='master',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='master',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userparcours',
            name='courses',
            field=models.ManyToManyField(related_name='courses', to='parcours_imi.Course'),
        ),
        migrations.AlterField(
            model_name='userparcours',
            name='formula',
            field=models.CharField(choices=[('3A-ecole', '3A École'), ('3A-M2-PFE', '3A M2 Imbriqués - Option 1'), ('3A-M2-ECTS', '3A M2 Imbriqués - Option 2')], max_length=120),
        ),
    ]
