# Generated by Django 2.0.6 on 2018-06-05 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0007_auto_20180605_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='master',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='parcours_imi.Master'),
        ),
        migrations.AlterField(
            model_name='userparcours',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parcours', to=settings.AUTH_USER_MODEL),
        ),
    ]
