# Generated by Django 2.0.6 on 2018-06-05 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0008_auto_20180605_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='short_name',
            field=models.CharField(default='', max_length=6, verbose_name='Nom court'),
            preserve_default=False,
        ),
    ]
