# Generated by Django 2.0.6 on 2018-06-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcours_imi', '0009_master_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
